name: 'setup crystal'
description: 'setup crystal, JavaScript based action'
author: 'MeilCli'
branding:
  icon: arrow-down-circle
  color: blue
inputs:
  crystal_version:
    description: 'install crystal version, will install latest version if no-value'
    required: true
    default: "latest"
  shards_version:
    description: 'install shards version, will install latest version if no-value'
    required: true
    default: "latest"
  github_token:
    description: 'github token, using get GitHub Release of crystal-lang/crystal or crystal-lang/shards'
    required: true
outputs:
  installed_crystal_json:
    description: 'installed crystal asset of crystal-lang/crystal Release'
  installed_shards_json:
    description: 'installed shards asset of crystal-lang/shards Release'
runs:
  using: 'node12'
  main: 'lib/main.js'