name: 'setup crystal'
description: 'setup crystal, JavaScript based action'
author: 'MeilCli'
branding:
  icon: arrow-down-circle
  color: blue
inputs:
  crystal_version:
    description: 'install crystal version, will install latest version if no-value'
    required: true
    default: 'latest'
  shards_version:
    description: 'install shards version, will install latest version if no-value'
    required: true
    default: 'latest'
  github_token:
    description: 'github token, using get GitHub Release of crystal-lang/crystal or crystal-lang/shards'
    default: ${{ github.token }}
  cache_mode:
    description: 'cache mode, value: none, tool-cache or cache, default: cache'
  cache_prefix:
    description: 'if selected cache on cache_mode, option that prefix of cache key'
  install_root:
    description: 'if selected none or cache on cache_mode, use directory that dicide at this option'
    default: ${{ runner.temp }}
outputs:
  installed_crystal_json:
    description: 'installed crystal asset of crystal-lang/crystal Release'
  installed_shards_json:
    description: 'installed shards asset of crystal-lang/shards Release'
runs:
  using: 'node16'
  main: 'dist/main/index.js'
  post: 'dist/post/index.js'
