name: CI

on: 
  push:
    branches:    
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install, build and test
      run: |
        npm install
        npm run build
        npm run test
      env:
        CI: true
  danger:
    runs-on: ubuntu-latest
    if: github.event_name  == 'pull_request'
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - name: npm install
      run: |
        npm install
      env:
        CI: true
    - uses: MeilCli/danger-action@v1
      with:
        plugins_file: 'Gemfile'
        danger_file: 'Dangerfile'
        danger_id: 'danger-pr'
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  test:
    if: github.event_name  != 'pull_request'
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, macOS-10.14]
        crystal: [0.31.0, 0.31.1]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: MeilCli/setup-crystal-action@master
        with: 
          crystal_version: ${{ matrix.crystal }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: MeilCli/test-command-action@master
        name: Check Crystal Version
        with:
          command: crystal version
          expect: '.+?Crystal\s${{ matrix.crystal }}.+?'
      - run: |
          shards --version
          echo 'puts "Hello Crystal"' > hello.cr
          crystal run hello.cr
