name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: npm run build
      - run: npm run test
      - run: npm run pack
        if: github.event_name != 'pull_request'
      - name: Create Pull Request
        if: github.event_name != 'pull_request'
        uses: peter-evans/create-pull-request@v2
        with:
          commit-message: 'update actions'
          title: 'update actions'
          labels: 'Action'
          assignees: 'MeilCli'
          reviewers: 'MeilCli'
          branch: 'update/action'
  test:
    if: github.event_name  != 'pull_request'
    strategy:
      matrix:
        include:
          # latest, latest
          - os: ubuntu-16.04
            crystal: latest
            shards: latest
          - os: ubuntu-18.04
            crystal: latest
            shards: latest
          - os: macos-10.15
            crystal: latest
            shards: latest
          # 0.35.0, 0.12.0
          # shards 0.12.0 has breaking change, shards 0.12.0 needs crystal 0.35.0
          - os: ubuntu-16.04
            crystal: 0.35.0
            shards: 0.12.0
          - os: ubuntu-18.04
            crystal: 0.35.0
            shards: 0.12.0
          - os: macos-10.15
            crystal: 0.35.0
            shards: 0.12.0
          # 0.35.0, 0.11.0
          # crystal 0.35.0 has breaking change, crystal 0.35.0 need shards 0.11.0
          - os: ubuntu-16.04
            crystal: 0.35.0
            shards: 0.11.0
          - os: ubuntu-18.04
            crystal: 0.35.0
            shards: 0.11.0
          - os: macos-10.15
            crystal: 0.35.0
            shards: 0.11.0
          # 0.34.0, 0.10.0
          # crystal 0.34.0 has breaking change, shards 0.10.0 needs crsytal 0.34.0
          # ubuntu-18.04 fails shards 0.10.0: https://forum.crystal-lang.org/t/compiling-an-app-to-work-on-both-ubuntu-16-and-18/328
          - os: ubuntu-16.04
            crystal: 0.34.0
            shards: 0.10.0
          - os: macos-10.15
            crystal: 0.34.0
            shards: 0.10.0
          # 0.33.0, 0.9.0
          - os: ubuntu-16.04
            crystal: 0.33.0
            shards: 0.9.0
          - os: ubuntu-18.04
            crystal: 0.33.0
            shards: 0.9.0
          - os: macos-10.15
            crystal: 0.33.0
            shards: 0.9.0
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          crystal_version: ${{ matrix.crystal }}
          shards_version: ${{ matrix.shards }}
          cache_prefix: '${{ matrix.os }}-${{ matrix.crystal }}-${{ matrix.shards }}-'
      - run: crystal version
      - run: shards --version
      - uses: MeilCli/test-command-action@v1
        if: matrix.crystal != 'latest'
        name: Check Crystal Version
        with:
          command: crystal version
          expect_contain: 'Crystal ${{ matrix.crystal }}'
      - uses: MeilCli/test-command-action@v1
        if: matrix.shards != 'latest'
        name: Check Shards Version
        with:
          command: shards --version
          expect_contain: 'Shards ${{ matrix.shards }}'
      - name: Run Crystal
        run: |
          echo 'puts "Hello Crystal"' > hello.cr
          crystal run hello.cr
